apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "a59274af566a485a56ba984697e8e61defe34058"
    spec:
      containers:
      - image: "shocnt/ads-service:a59274af566a485a56ba984697e8e61defe34058"
        name: advertisements
