apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "850f1813425714c4baf658679ce7f099c344dbea"
    spec:
      containers:
      - image: "shocnt/ads-service:850f1813425714c4baf658679ce7f099c344dbea"
        name: advertisements
