apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "ae18bb250b5fd984c01ffcc65f1608ddf29017ce"
    spec:
      containers:
      - image: "shocnt/ads-service:ae18bb250b5fd984c01ffcc65f1608ddf29017ce"
        name: advertisements
