apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "4581f8f6a878a725a81d06009e5b7e91321cdbaa"
    spec:
      containers:
      - image: "shocnt/ads-service:4581f8f6a878a725a81d06009e5b7e91321cdbaa"
        name: advertisements
