apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "0dd625234738b8a9b50ade904dea5626500d527a"
    spec:
      containers:
      - image: "shocnt/ads-service:0dd625234738b8a9b50ade904dea5626500d527a"
        name: advertisements
