apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "58611e47c3f15c2da59e430bdd9bb95b681d376f"
    spec:
      containers:
      - image: "shocnt/ads-service:58611e47c3f15c2da59e430bdd9bb95b681d376f"
        name: advertisements
