apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "2.0"
    spec:
      containers:
      - image: "shocnt/ads-service:v2"
        name: advertisements
