apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "3eb2a3889407aff3e2a53ad2c4c96f065fdcec82"
    spec:
      containers:
      - image: "shocnt/ads-service:3eb2a3889407aff3e2a53ad2c4c96f065fdcec82"
        name: advertisements
