apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/version: "1.1"
  name: advertisements
spec:
  selector:
    matchLabels:
      tags.datadoghq.com/version: "1.1"
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "1.1"
    spec:
      containers:
      - image: "shocnt/ads-service:v2"
        name: advertisements
