apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "f6e44102409250ead7af721a948bca5508b65b91"
    spec:
      containers:
      - image: "shocnt/ads-service:f6e44102409250ead7af721a948bca5508b65b91"
        name: advertisements
