apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: "f205a5563b03665e57f49ca9a1f3c5215b472be1"
    spec:
      containers:
      - image: "shocnt/ads-service:f205a5563b03665e57f49ca9a1f3c5215b472be1"
        name: advertisements
