apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: advertisements
spec:
  template:
    spec:
      containers:
      - image: "shocnt/ads-service:v2"
        name: advertisements
        env:
          - name: DD_VERSION
            value: "2.0"
