apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: advertisements
spec:
  replicas: 4
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  strategy:
    canary:
      steps:
      - setWeight: 100
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "7032dbb35f6b851181aece84febb3094188aa5e6"
    spec:
      containers:
      - image: "shocnt/ads-service:7032dbb35f6b851181aece84febb3094188aa5e6"
        name: advertisements
