apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: staging
  name: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      tags.datadoghq.com/env: staging
  strategy:
    canary:
      steps:
      - setWeight: 100
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: staging
        tags.datadoghq.com/version: "c7fb4473c9c31769057ceb56677fd9cc9d0add5c"
    spec:
      containers:
      - image: "shocnt/ads-service:c7fb4473c9c31769057ceb56677fd9cc9d0add5c"
        name: advertisements
