apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: staging
  name: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      tags.datadoghq.com/env: staging
  strategy:
    canary:
      steps:
      - setWeight: 100
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: staging
        tags.datadoghq.com/version: "e51d60b48ffb10238c85284d029fb88f95e29337"
    spec:
      containers:
      - image: "shocnt/ads-service:e51d60b48ffb10238c85284d029fb88f95e29337"
        name: advertisements
