apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: advertisements
spec:
  replicas: 4
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  strategy:
    canary:
      analysis:
        templates:
        - templateName: trace-error-rate
        startingStep: 1
        args:
        - {name: service-name, value: advertisements-service}
        - {name: version, value: "aacba1c71586d6a8b37441193e7d4d2d04dc87c1"}
      steps:
      - setWeight: 25
      - pause: {duration: 5m}
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "aacba1c71586d6a8b37441193e7d4d2d04dc87c1"
    spec:
      containers:
      - image: "shocnt/ads-service:aacba1c71586d6a8b37441193e7d4d2d04dc87c1"
        name: advertisements
