apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: advertisements
spec:
  replicas: 4
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  strategy:
    canary:
      analysis:
        templates:
        - templateName: trace-error-rate
        startingStep: 1
        args:
        - {name: service-name, value: advertisements-service}
        - {name: version, value: "c7fb4473c9c31769057ceb56677fd9cc9d0add5c"}
      steps:
      - setWeight: 25
      - pause: {duration: 10m}
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "c7fb4473c9c31769057ceb56677fd9cc9d0add5c"
    spec:
      containers:
      - image: "shocnt/ads-service:c7fb4473c9c31769057ceb56677fd9cc9d0add5c"
        name: advertisements
