apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    tags.datadoghq.com/env: prod
  name: advertisements
spec:
  replicas: 4
  selector:
    matchLabels:
      tags.datadoghq.com/env: prod
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {}
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/version: "963049cd44fcdd830b574adfec63e914d2483130"
    spec:
      containers:
      - image: "shocnt/ads-service:963049cd44fcdd830b574adfec63e914d2483130"
        name: advertisements
