apiVersion: v1
kind: Service
metadata:
  labels:
    tags.datadoghq.com/service: advertisements-service
    tags.datadoghq.com/env: development
    app: ecommerce
  name: advertisements-experiment
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    tags.datadoghq.com/service: advertisements-service
    tags.datadoghq.com/env: development
    app: ecommerce
    deploy: experiment
