apiVersion: v1
kind: Service
metadata:
  labels:
    tags.datadoghq.com/service: advertisements-service
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "1.0"
    app: ecommerce
  name: advertisements
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    tags.datadoghq.com/service: advertisements-service
    tags.datadoghq.com/env: development
    tags.datadoghq.com/version: "1.0"
    app: ecommerce
